//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.15 at 12:34:30 dop. CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "info:fedora/fedora-system:def/foxml#",
xmlns = {   
        @XmlNs(namespaceURI = "info:fedora/fedora-system:def/foxml#", prefix = "foxml")                    
    },   
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package info.fedora.foxml.v1;

import javax.xml.bind.annotation.XmlNs; 	